eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

server:
  port: 9001

spring:
  application:
    name: service-zuul

zuul:
  routes:
    #/api-auth/ 开头匹配到tgshop-auth-service
    api-auth:
      path: /api-auth/**
      serviceId: tgshop-auth-service
    #/api-categories/ 开头匹配到tgshop-auth-service
    api-categories:
      path: /api-categories/**
      serviceId: tgshop-categories-service
    #/api-product/ 开头匹配到service-producer
    api-product:
      path: /api-product/**
      serviceId: tgshop-product-service
    # /api-seller  tgshop-manager-seller
    api-seller:
      path: /api-seller/**
      serviceId: tgshop-manager-seller
    #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://github.com/