server:
  port: 9092

spring:
  application:
    name: tgshop-manager-seller

  #redis
  redis:
    host: 192.168.116.128
    port: 6379

  #datasource
  datasource:
    url: jdbc:mysql://localhost:3306/tgshop_cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  #jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/


feign:
  hystrix:
    enabled: true

tgshop:
  swagger:
    enable: true
  conf:
    goodsAuditEnable: false
